project_dir: /Users/david.neufeld/repos/csbCrawler2Cloud/
#data_dir: /Users/david.neufeld/data/CSB/ROSEP
data_dir: /Users/david.neufeld/repos/csbCrawler2Cloud/data/
output_dir: /Users/david.neufeld/data/CSB/reprocessed/
bucket: "csbxyzfiles"