project_dir: /Users/dneufeld/repos/csbCrawler2Cloud/
#data_dir: /Users/david.neufeld/data/CSB/ROSEP
data_dir: /Users/dneufeld/repos/csbCrawler2Cloud/data/
output_dir: /Users/dneufeld/repos/csbCrawler2Cloud/output/
bucket: "csbxyzfiles"