# _dirs should end in '/'. Relative dirs are relative to the CSBCRAWLER environment variable.
data_dir: data/input/
test_data_dir: data/input/
output_dir: data/reprocessed/
manifest_dir: manifestdir/
enable_upload: false
bucket: "odp-noaa-nesdis-ncei-test"
