project_dir: /Users/dneufeld/repos/csbCrawler2Cloud/
data_dir: /Users/dneufeld/repos/csbCrawler2Cloud/data/
test_data_dir: /Users/dneufeld/repos/csbCrawler2Cloud/data/
output_dir: /Users/dneufeld/repos/csbCrawler2Cloud/data/reprocessed/
bucket: "odp-noaa-nesdis-ncei-test"
