# Create a csbCrawler2Cloud/config/credentials.yaml file from this sample.
# Real credentials are not checked in to the repository for security.
ACCESS_KEY : "fill_in_access"
SECRET_KEY : "fill_in_secret"